# Jun Sok Huhh / 허준석

Lead (acting), Data Center

12 Daewangpangyo-ro 644beon-gil &#183; NCSOFT &#183; Seongnam Gyeonggi, South Korea 13494 

[mail4work](junsokhuhh@ncsoft.com) &#183;[mail4personal](anarinsk@gmail.com) &#183;[github](https://github.com/anarinsk) &#183; [blog](http://lostineconomics.com) &vert; updated: December 30, 2019

## Employment

*NCSOFT*, Lead (acting), Data Center (Seongnam Gyeonggi  &#183; South Korea) 2019.02--present 

*NCSOFT*, Lead, I&I Division (Seongnam Gyeonggi  &#183; South Korea) 2018.03--2019.01 

*NCSOFT*, Lead, R&I Team (Seongnam Gyeonggi  &#183; South Korea) 2014.08--2018.03

*KISDI*$^*$, Senior Researcher (Jinchun Chungchungbuk  &#183; South Korea) 2013.05--2014.07
$^*$Korea Information Society Development Institute

*FourThirtyThree*, Data Anlysist (Seoul  &#183; South Korea) 2012--2013

*Seoul National University*, Postdoc. School of Economics (Seoul  &#183; South Korea) 2011--2012

## Education

*Seoul National University*, Ph.D. School of Economics 2010

*Seoul National University*, M.A. School of Economics 1997 

*Seoul National University*, B.A. School of Economics 1995

## Publications

### Books and book chapters 

Jun Sok Huhh. 2009. "The Evolution of PC bang Culture in Korea (Chapter 7)." *Gaming Cultures and Place in Asia-Pacific* [edited by Larissa Hjorth, Dean Chan]. Routledge.

Jun Sok Huhh. 2006. *Business of Fun–Economics of computer games industry*. ChekSeSang. [Korean language]

### Journal articles

Jun Sok Huhh and Jeong Wook Byun. 2017. "North Korea’s Nuclear Weapon Development and South Korea’s Strategic Reaction: A Signaling Game Approach." *Ehwa Journal of Social Sciences* 33(1): 107--142. [Korean language]

Jun Sok Huhh and Jung-Kyu Choi. 2012. "The Decay in Contributions in a Public Goods Game: Learning Hypothesis, Strategy Hypothesis and Reciprocity Hypothesis Revisited." *Journal of Econometric Theory and Econometrics* 23(2):165--186. [Korean language]

Jun Sok Huhh. 2008. "Culture and Business of PC Bangs in Korea." *Games and Culture* 3(1):26--37.

## Technical Skills 

### Proficient
R, Mathematica, $\rm \LaTeX$

### Familiar
Python, NetLogo, Docker

<br>
<br>
<br>
[lostineconomics.com](http://lostineconomics.com) | Jun Sok Huhh 
