project:
  type: website
  output-dir: docs
website:
  title: "lostineconomics.com"
  margin-footer: "subscribe.html"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/anarinsk
      - icon: twitter
        href: https://twitter.com/anarinsk
      - icon: rss
        href: index.xml
format:
  html:
    theme: yeti
    css: styles.css