project:
  type: website
  output-dir: docs
website:
  title: "lostineconomics.com"
  site-url: https://www.lostineconomics.com/
  description: "Another useless blog"
  favicon: "favicon.ico"
  navbar:
    right:
      - text: "Books"
        href: https://books.lostineconomics.com
      - project.qmd
      - research.qmd
      - about.qmd
      - icon: github
        href: https://github.com/anarinsk
      - icon: twitter
        href: https://twitter.com/anarinsk
      - icon: rss
        href: index.xml
lightbox: auto
format:
  html:
    #resources: 
    #  - "fonts.html"
    include-before-body: "google_analytics.html"
    theme:
        light: [cosmo, theme.scss, anari-custom.scss]
        dark: [cosmo, theme-dark.scss, anari-custom.scss]
    highlight-style: github
    #code-line-numbers: true
    code-block-bg: true
    code-block-border-left: "#31BAE9"
excute: 
  cache: true 
