[project]
name = "lostineconomics_quarto"
version = "0.1.0"
description = "Add a short description here"
authors = ["Junsok Huhh <anarinsk@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64"]

[tasks]

[target.linux-64.dependencies]
python = "3.11.*"

[target.osx-arm64.dependencies]
python = "3.11.*"

[dependencies]
scipy = "1.11.3.*"
seaborn = "0.13.0.*"
matplotlib = "3.8.0.*"
python = "3.11.*"
pandas = "2.1.1.*"
statsmodels = "0.14.0.*"
jupyter = "1.0.0.*"

[pypi-dependencies]
stargazer = "*"
koreanize-matplotlib = "*"
