[project]
name = "lostineconomics_quarto"
version = "0.1.0"
description = "Add a short description here"
authors = ["Junsok Huhh <anarinsk@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
matplotlib = "3.8.0.*"
python = "3.11.*"
pandas = "2.1.1.*"
scipy = "1.11.3.*"
seaborn = "0.13.0.*"
statsmodels = "0.14.0.*"
jupyter = "1.0.0.*"
r-stargazer = "5.2.3.*"
