---
title:  수입은 GDP에 영향을 주는가? 
description: GDP 항등식을 오해하지 말자  
author: "JS HUHH"
date: "04/29/2022"
image: "images/econcat_2.jfif"
categories: [economics, econ-simple]
#margin-header: subscribe.html
---

## 오해 

GDP 항등식에 관한 오해는 경제 저널리즘에서 잘 생기는 오해다. 어제 뉴욕 타임스 사설에 이걸 오해한 내용이 실렸고, 트위터 등에서 여러 경제학자들이 이 사실을 지적했다. GDP 항등식에서 시작해보자. 국내총생산이라는 GDP 항등식은 아래와 같이 제시된다. 

$$
Y = C + I + G + X - M
$$

|항목|내용|
|:--:|:--:|
|$C$|국내 총소비|
|$I$|국내 총투자|
|$G$|정부 지출|
|$X$|수출|
|$M$|수입|

저 항등식만 보면 수입이 줄면 $Y$가 늘 것 같다. 그런데 이건 오해다. 두 가지 측면에서 생각을 해보자. 

1. GDP는 '국내' 총생산이다. 즉, 1년 동안 국내에서 생산된 재화와 서비스의 총량을 측정한다. 그런데 수입품은 국내에서 생산된 것이 아니다. 따라서 빼주는 게 맞다. 
2. 그런데 수입이 줄면 GDP가 주는 게 아닌가? 아니다. 왜냐하면 앞에 $C$, $I$, $G$는 각각 수입품에 관한 소비, 투자, 정부 지출을 포함하고 있기 때문이다. 즉, $C = C_{d} + C_{m}$, 즉 국내에서 생산된 제품에 관한 소비($C_d$)와 해외에서 생산된 소비($C_m$)을 포함하고 있다. GDP란 국내 총생산을 측정하는 것이므로 $C_m$을 빼주는 게 맞다. 

즉, 식을 재구성해보면 이렇다. 

$$
(C_d + I_d + G_d) + \overbrace{(C_m + I_m + G_m)}^{M} + X - M 
$$

정의상 $C_m + I_m + G_m = M$이 되기 때문에 M이 늘고 주는 것은 GDP에 아무런 영향을 주지 않는다. GDP를 측정하기 위한 회계상의 이유로 $M$이 들어간 것이지 $M$의 변화가 독자적으로 GDP를 변화시키지는 않는다. 

## 다른 주장 

Noahpinion에서 예시했듯이 이렇게 볼 수도 있을 것이다. 

> 만일 수입품을 쓰지 않았더라면 그 만큼 국내에서 생산된 제품을 대신 쓰지 않았겠는가? 따라서 수입을 줄이거나 금지시키면 이에 따라서 국내 총생산이 늘게 될 것이다. 

이는 사실 트럼프 진영의 주장이기도 하다. 이러한 주장은 두 가지 차원에서 반박할 수 있다. 먼저 실증의 차원이다. 저 말이 맞다면 수입이 줄 때 GDP는 늘어나는 경향이 있을 것이고 반대로 수입이 늘면 GDP는 줄 것이다. 그런데 자료를 보면 전혀 그렇지 않다. 미국이나 한국이나 오히려 공행하는 듯 싶다. 

미국의 GDP, 수입 증가율 변화 
<iframe src="https://fred.stlouisfed.org/graph/graph-landing.php?g=OHlj&width=670&height=475" scrolling="no" frameborder="0" style="overflow:hidden; width:670px; height:525px;" allowTransparency="true" loading="lazy"></iframe>

한국의 GDP, 수입 증가율 변화 
<iframe src="https://fred.stlouisfed.org/graph/graph-landing.php?g=OHln&width=670&height=475" scrolling="no" frameborder="0" style="overflow:hidden; width:670px; height:525px;" allowTransparency="true" loading="lazy"></iframe>


다음은 논리의 차원이다. 무역은 비교우위의 원리에 따라서 발생한다. 즉, 해외에서 어떤 제품을 수입했다면 그것이 국내 생산보다 경쟁력이 있기 때문이다. 중국산을 막고 이를 한국산으로 대체했다면 해당 제품을 생산하는 기업의 매출이 증가하고 이는 GDP 증가에 기여할 것이다. 하지만 해당 제품의 수입을 통해서 누리던 효율성이 사라지면서 GDP를 감소시키게 된다. GDP 증가와 감소 중 어느 쪽이 더 클지 미리 정할 수는 없다. 수입이 효율성의 논리에 의해 결정된 것이라면 인위적인 수입대체는 GDP를 감소시키게 될 것이다(자중손실). 

:::{.column-margin}
이는 일국의 '총량적인' 차원에서 하는 이야기라는 점을 지적해두겠다. 예를 들어 무역이 고용이 미치는 영향은 경제적 후생(소비자 잉여 + 생산자 잉여)만으로 판단하기에는 보다 미묘하다. 예를 들어 중국산 철강 때문에 미국 러스트 벨트의 고용이 대체되었다고 하자. 이것이 총량적으로 효율성의 증가라고 해도, 고용과 실업 차원에서는 구성의 큰 변화가 발생한다. 적어도 경제원론 차원에서는 총량적인 효율성을 추구하고 이러한 변화에 따른 자원 배분은 어떤 주체(국가)가 임의로 달성할 수 있다고 가정하는 경향이 있다. 물론 오늘날의 보다 현실적이고 정교한 경제학은 이렇게 생각하지 않는다. 
:::

## 참고 

Noahpinion, [Imports do not subtract from GDP](https://noahpinion.substack.com/p/imports-do-not-subtract-from-gdp?s=r)



